[REPOSITORY] Implement a repository for the user + DTOes
jv-sep-23-group3/car-sharing-app pull request #15
Opened 2024-01-11 18:00 UTC by OlexVoit

2024-01-11 19:44 UTC, ponomvrenko requested changes

2024-01-11 19:44 UTC, ponomvrenko commented on src/main/java/mate/sep23/group3/car/sharing/dto/user/UserRegistrationRequestDto.java
> +    @NotBlank(message = NOT_BE_NULL)
Add @NotNull

2024-01-11 19:44 UTC, ponomvrenko commented on src/main/java/mate/sep23/group3/car/sharing/dto/user/UserRegistrationRequestDto.java
> +    @NotBlank(message = NOT_BE_NULL)
Add @NotNull

2024-01-11 19:44 UTC, ponomvrenko commented on src/main/java/mate/sep23/group3/car/sharing/validation/FieldMatch.java
> +@Target(ElementType.TYPE)
`ElementType.FIELD`

2024-01-11 19:44 UTC, ponomvrenko commented on src/main/java/mate/sep23/group3/car/sharing/validation/PasswordMatchesValidator.java
> +    public boolean isValid(UserRegistrationRequestDto user,
user -> requestDto

2024-01-11 19:44 UTC, ponomvrenko commented on src/main/java/mate/sep23/group3/car/sharing/validation/PasswordMatchesValidator.java
> +        return user.getPassword() != null
`return reuestDto.getPassword().equals(requestDto.getRepeatedPassword)`

2024-01-12 08:18 UTC, ponomvrenko requested changes

2024-01-12 08:18 UTC, ponomvrenko commented on src/main/java/mate/sep23/group3/car/sharing/security/JwtUtil.java
> +            return false;
We should throw here `throw new JwtException("Expired or invalid JWT token!");` to notificate our user about exception type reason

2024-01-12 08:22 UTC, ponomvrenko requested changes

2024-01-12 08:22 UTC, ponomvrenko commented on src/main/java/mate/sep23/group3/car/sharing/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith(TOKEN_START)) {
Please change the naming of the constant to `BEARER_PREFIX`

2024-01-12 08:23 UTC, ponomvrenko commented
Well done! Please pay attention to my minor comments

2024-01-12 09:52 UTC, ponomvrenko approved these changes
Well done! LGTM

2024-01-12 09:56 UTC, dima-semeniuk approved these changes
Great job!

2024-01-12 09:57 UTC, merged