[PAYMENT] Added the ability to pay for car rental
jv-sep-23-group3/car-sharing-app pull request #27
Opened 2024-01-14 14:19 UTC by HovorukhaBohdan

2024-01-14 16:25 UTC, dima-semeniuk reviewed
Great job, but minor points to be considered

2024-01-14 16:25 UTC, dima-semeniuk commented on src/main/java/mate/sep23/group3/car/sharing/repository/PaymentRepository.java
> +    Page<Payment> findAllByRentalIn(List<Rental> rentals, Pageable pageable);
I think there should be findAllByRentalId

2024-01-14 16:25 UTC, dima-semeniuk commented on src/main/java/mate/sep23/group3/car/sharing/strategy/payment/handlers/roles/CustomerRoleHandler.java
> +        return paymentRepository.findAllByRentalIn(rentals, pageable);
```suggestion
        return paymentRepository.findAllByRentalId(rentals, pageable);
```

2024-01-15 08:00 UTC, dima-semeniuk approved these changes
Great job! Nothing to add

2024-01-15 08:14 UTC, ponomvrenko requested changes
Good job! A small point needs to be made.

2024-01-15 08:14 UTC, ponomvrenko commented on pom.xml
> +        </dependency>
Redundant. We have already swagger in our:
```
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
    <version>2.2.0</version>
</dependency>
```

2024-01-15 09:12 UTC, ponomvrenko approved these changes
LGTM!

2024-01-15 09:13 UTC, merged